stages:
  data_ingestion:
    cmd: python src/ml_project/components/data_ingestion.py
    deps:
      - src/ml_project/components/data_ingestion.py
    params:
      - data_ingestion.test_size
    outs:
      - data/raw
  data_preprocessing:
    cmd: python src/ml_project/components/data_preprocessing.py
    deps:
      - src/ml_project/components/data_preprocessing.py
      - data/raw
    outs:
      - data/preprocessed
  feature_engineering:
    cmd: python src/ml_project/components/feature_engineering.py
    deps:
      - src/ml_project/components/feature_engineering.py
      - data/preprocessed
    outs:
      - data/feature
      - data/models/standard_scaler.pkl
  model_building:
    cmd: python src/ml_project/components/model_building.py
    deps:
      - src/ml_project/components/model_building.py
      - data/feature
    params:
      - model_building.learning_rate
      - model_building.max_depth
      - model_building.min_child_samples
      - model_building.n_estimators
      - model_building.num_leaves
      - model_building.n_iter
    outs:
      - models/lgbm_model.pkl
  model_evaluation:
    cmd: python src/ml_project/components/model_evaluation.py
    deps:
      - src/ml_project/components/model_evaluation.py
      - models/lgbm_model.pkl
    metrics:
      - metrics.json